specVersion: 0.2.0
name: fizen-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x18e5b59ea1242150f57b2f400985e176f2a193b17fdc99569d20b0a16eef6ef8'
  endpoint: wss://13.229.32.165:443
  chaintypes:
    file: types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
#          filter:
#            module: balances
#            method: Deposit
#        - handler: handleCall
#          kind: substrate/CallHandler
